//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CvssType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CvssType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseScore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttackVector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttackComplexity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Confidentiality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExploitCodeMaturity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemediationLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportConfidence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConfidentialityRequirement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IntegrityRequirement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AvailabilityRequirement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CvssType", propOrder = {
    "baseScore",
    "attackVector",
    "attackComplexity",
    "confidentiality",
    "availability",
    "exploitCodeMaturity",
    "remediationLevel",
    "reportConfidence",
    "confidentialityRequirement",
    "integrityRequirement",
    "availabilityRequirement",
    "version"
})
public class CvssType {

    @XmlElement(name = "BaseScore", required = true)
    protected String baseScore;
    @XmlElement(name = "AttackVector", required = true)
    protected String attackVector;
    @XmlElement(name = "AttackComplexity", required = true)
    protected String attackComplexity;
    @XmlElement(name = "Confidentiality", required = true)
    protected String confidentiality;
    @XmlElement(name = "Availability", required = true)
    protected String availability;
    @XmlElement(name = "ExploitCodeMaturity", required = true)
    protected String exploitCodeMaturity;
    @XmlElement(name = "RemediationLevel", required = true)
    protected String remediationLevel;
    @XmlElement(name = "ReportConfidence", required = true)
    protected String reportConfidence;
    @XmlElement(name = "ConfidentialityRequirement", required = true)
    protected String confidentialityRequirement;
    @XmlElement(name = "IntegrityRequirement", required = true)
    protected String integrityRequirement;
    @XmlElement(name = "AvailabilityRequirement", required = true)
    protected String availabilityRequirement;
    @XmlElement(name = "Version")
    protected byte version;

    /**
     * Gets the value of the baseScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseScore() {
        return baseScore;
    }

    /**
     * Sets the value of the baseScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseScore(String value) {
        this.baseScore = value;
    }

    /**
     * Gets the value of the attackVector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttackVector() {
        return attackVector;
    }

    /**
     * Sets the value of the attackVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttackVector(String value) {
        this.attackVector = value;
    }

    /**
     * Gets the value of the attackComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttackComplexity() {
        return attackComplexity;
    }

    /**
     * Sets the value of the attackComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttackComplexity(String value) {
        this.attackComplexity = value;
    }

    /**
     * Gets the value of the confidentiality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentiality() {
        return confidentiality;
    }

    /**
     * Sets the value of the confidentiality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentiality(String value) {
        this.confidentiality = value;
    }

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailability(String value) {
        this.availability = value;
    }

    /**
     * Gets the value of the exploitCodeMaturity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExploitCodeMaturity() {
        return exploitCodeMaturity;
    }

    /**
     * Sets the value of the exploitCodeMaturity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExploitCodeMaturity(String value) {
        this.exploitCodeMaturity = value;
    }

    /**
     * Gets the value of the remediationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemediationLevel() {
        return remediationLevel;
    }

    /**
     * Sets the value of the remediationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemediationLevel(String value) {
        this.remediationLevel = value;
    }

    /**
     * Gets the value of the reportConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportConfidence() {
        return reportConfidence;
    }

    /**
     * Sets the value of the reportConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportConfidence(String value) {
        this.reportConfidence = value;
    }

    /**
     * Gets the value of the confidentialityRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialityRequirement() {
        return confidentialityRequirement;
    }

    /**
     * Sets the value of the confidentialityRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialityRequirement(String value) {
        this.confidentialityRequirement = value;
    }

    /**
     * Gets the value of the integrityRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrityRequirement() {
        return integrityRequirement;
    }

    /**
     * Sets the value of the integrityRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrityRequirement(String value) {
        this.integrityRequirement = value;
    }

    /**
     * Gets the value of the availabilityRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityRequirement() {
        return availabilityRequirement;
    }

    /**
     * Sets the value of the availabilityRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityRequirement(String value) {
        this.availabilityRequirement = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(byte value) {
        this.version = value;
    }

}
