//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LicenseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LicenseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReferenceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoyaltyFree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CopyrightRiskScore" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="RiskLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Linking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CopyLeft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PatentRiskScore" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PackageUsageCount" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="IsViolatingPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicenseType", propOrder = {
    "referenceType",
    "reference",
    "royaltyFree",
    "copyrightRiskScore",
    "riskLevel",
    "linking",
    "copyLeft",
    "patentRiskScore",
    "name",
    "url",
    "packageUsageCount",
    "isViolatingPolicy"
})
public class LicenseType {

    @XmlElement(name = "ReferenceType")
    protected String referenceType;
    @XmlElement(name = "Reference")
    protected String reference;
    @XmlElement(name = "RoyaltyFree")
    protected String royaltyFree;
    @XmlElement(name = "CopyrightRiskScore")
    protected Byte copyrightRiskScore;
    @XmlElement(name = "RiskLevel")
    protected String riskLevel;
    @XmlElement(name = "Linking")
    protected String linking;
    @XmlElement(name = "CopyLeft")
    protected String copyLeft;
    @XmlElement(name = "PatentRiskScore")
    protected Byte patentRiskScore;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Url")
    protected String url;
    @XmlElement(name = "PackageUsageCount")
    protected Short packageUsageCount;
    @XmlElement(name = "IsViolatingPolicy")
    protected String isViolatingPolicy;

    /**
     * Gets the value of the referenceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * Sets the value of the referenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceType(String value) {
        this.referenceType = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the royaltyFree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoyaltyFree() {
        return royaltyFree;
    }

    /**
     * Sets the value of the royaltyFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoyaltyFree(String value) {
        this.royaltyFree = value;
    }

    /**
     * Gets the value of the copyrightRiskScore property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getCopyrightRiskScore() {
        return copyrightRiskScore;
    }

    /**
     * Sets the value of the copyrightRiskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setCopyrightRiskScore(Byte value) {
        this.copyrightRiskScore = value;
    }

    /**
     * Gets the value of the riskLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskLevel() {
        return riskLevel;
    }

    /**
     * Sets the value of the riskLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskLevel(String value) {
        this.riskLevel = value;
    }

    /**
     * Gets the value of the linking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinking() {
        return linking;
    }

    /**
     * Sets the value of the linking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinking(String value) {
        this.linking = value;
    }

    /**
     * Gets the value of the copyLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyLeft() {
        return copyLeft;
    }

    /**
     * Sets the value of the copyLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyLeft(String value) {
        this.copyLeft = value;
    }

    /**
     * Gets the value of the patentRiskScore property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPatentRiskScore() {
        return patentRiskScore;
    }

    /**
     * Sets the value of the patentRiskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPatentRiskScore(Byte value) {
        this.patentRiskScore = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the packageUsageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPackageUsageCount() {
        return packageUsageCount;
    }

    /**
     * Sets the value of the packageUsageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPackageUsageCount(Short value) {
        this.packageUsageCount = value;
    }

    /**
     * Gets the value of the isViolatingPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsViolatingPolicy() {
        return isViolatingPolicy;
    }

    /**
     * Sets the value of the isViolatingPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsViolatingPolicy(String value) {
        this.isViolatingPolicy = value;
    }

}
