//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SCARiskReport_QNAME = new QName("", "SCA-Risk-Report");
    private final static QName _LicensesTypeLicenseCopyLeft_QNAME = new QName("", "CopyLeft");
    private final static QName _LicensesTypeLicenseReference_QNAME = new QName("", "Reference");
    private final static QName _LicensesTypeLicensePackageUsageCount_QNAME = new QName("", "PackageUsageCount");
    private final static QName _LicensesTypeLicenseRoyaltyFree_QNAME = new QName("", "RoyaltyFree");
    private final static QName _LicensesTypeLicenseIsViolatingPolicy_QNAME = new QName("", "IsViolatingPolicy");
    private final static QName _LicensesTypeLicenseCopyrightRiskScore_QNAME = new QName("", "CopyrightRiskScore");
    private final static QName _LicensesTypeLicenseRiskLevel_QNAME = new QName("", "RiskLevel");
    private final static QName _LicensesTypeLicensePatentRiskScore_QNAME = new QName("", "PatentRiskScore");
    private final static QName _LicensesTypeLicenseReferenceType_QNAME = new QName("", "ReferenceType");
    private final static QName _LicensesTypeLicenseLinking_QNAME = new QName("", "Linking");
    private final static QName _LicensesTypeLicenseUrl_QNAME = new QName("", "Url");
    private final static QName _LicensesTypeLicenseName_QNAME = new QName("", "Name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LicensesType }
     * 
     */
    public LicensesType createLicensesType() {
        return new LicensesType();
    }

    /**
     * Create an instance of {@link SCARiskReportType }
     * 
     */
    public SCARiskReportType createSCARiskReportType() {
        return new SCARiskReportType();
    }

    /**
     * Create an instance of {@link PolicyType }
     * 
     */
    public PolicyType createPolicyType() {
        return new PolicyType();
    }

    /**
     * Create an instance of {@link ProjectPoliciesType }
     * 
     */
    public ProjectPoliciesType createProjectPoliciesType() {
        return new ProjectPoliciesType();
    }

    /**
     * Create an instance of {@link ViolatingEntitiesType }
     * 
     */
    public ViolatingEntitiesType createViolatingEntitiesType() {
        return new ViolatingEntitiesType();
    }

    /**
     * Create an instance of {@link CvssType }
     * 
     */
    public CvssType createCvssType() {
        return new CvssType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link LicensesLegalRiskType }
     * 
     */
    public LicensesLegalRiskType createLicensesLegalRiskType() {
        return new LicensesLegalRiskType();
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link LicenseType }
     * 
     */
    public LicenseType createLicenseType() {
        return new LicenseType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link ConditionsType }
     * 
     */
    public ConditionsType createConditionsType() {
        return new ConditionsType();
    }

    /**
     * Create an instance of {@link PackagesType }
     * 
     */
    public PackagesType createPackagesType() {
        return new PackagesType();
    }

    /**
     * Create an instance of {@link RiskReportSummaryType }
     * 
     */
    public RiskReportSummaryType createRiskReportSummaryType() {
        return new RiskReportSummaryType();
    }

    /**
     * Create an instance of {@link VulnerabilitiesType }
     * 
     */
    public VulnerabilitiesType createVulnerabilitiesType() {
        return new VulnerabilitiesType();
    }

    /**
     * Create an instance of {@link ViolatingConditionGroupsType }
     * 
     */
    public ViolatingConditionGroupsType createViolatingConditionGroupsType() {
        return new ViolatingConditionGroupsType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link PoliciesType }
     * 
     */
    public PoliciesType createPoliciesType() {
        return new PoliciesType();
    }

    /**
     * Create an instance of {@link VulnerabilityType }
     * 
     */
    public VulnerabilityType createVulnerabilityType() {
        return new VulnerabilityType();
    }

    /**
     * Create an instance of {@link ViolatingPackagesType }
     * 
     */
    public ViolatingPackagesType createViolatingPackagesType() {
        return new ViolatingPackagesType();
    }

    /**
     * Create an instance of {@link RulesType }
     * 
     */
    public RulesType createRulesType() {
        return new RulesType();
    }

    /**
     * Create an instance of {@link LicensesType.License }
     * 
     */
    public LicensesType.License createLicensesTypeLicense() {
        return new LicensesType.License();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SCARiskReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SCA-Risk-Report")
    public JAXBElement<SCARiskReportType> createSCARiskReport(SCARiskReportType value) {
        return new JAXBElement<SCARiskReportType>(_SCARiskReport_QNAME, SCARiskReportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CopyLeft", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseCopyLeft(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseCopyLeft_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reference", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseReference(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseReference_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PackageUsageCount", scope = LicensesType.License.class)
    public JAXBElement<Short> createLicensesTypeLicensePackageUsageCount(Short value) {
        return new JAXBElement<Short>(_LicensesTypeLicensePackageUsageCount_QNAME, Short.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RoyaltyFree", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseRoyaltyFree(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseRoyaltyFree_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsViolatingPolicy", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseIsViolatingPolicy(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseIsViolatingPolicy_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CopyrightRiskScore", scope = LicensesType.License.class)
    public JAXBElement<Byte> createLicensesTypeLicenseCopyrightRiskScore(Byte value) {
        return new JAXBElement<Byte>(_LicensesTypeLicenseCopyrightRiskScore_QNAME, Byte.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RiskLevel", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseRiskLevel(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseRiskLevel_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PatentRiskScore", scope = LicensesType.License.class)
    public JAXBElement<Byte> createLicensesTypeLicensePatentRiskScore(Byte value) {
        return new JAXBElement<Byte>(_LicensesTypeLicensePatentRiskScore_QNAME, Byte.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReferenceType", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseReferenceType(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseReferenceType_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linking", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseLinking(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseLinking_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Url", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseUrl(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseUrl_QNAME, String.class, LicensesType.License.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name", scope = LicensesType.License.class)
    public JAXBElement<String> createLicensesTypeLicenseName(String value) {
        return new JAXBElement<String>(_LicensesTypeLicenseName_QNAME, String.class, LicensesType.License.class, value);
    }

}
