//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rules" type="{}RulesType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PolicyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BreakBuild" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsViolating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsGlobal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsPredefined" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyType", propOrder = {
    "rules",
    "description",
    "policyName",
    "breakBuild",
    "isViolating",
    "isGlobal",
    "isPredefined"
})
public class PolicyType {

    @XmlElement(name = "Rules", required = true)
    protected RulesType rules;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "PolicyName", required = true)
    protected String policyName;
    @XmlElement(name = "BreakBuild", required = true)
    protected String breakBuild;
    @XmlElement(name = "IsViolating", required = true)
    protected String isViolating;
    @XmlElement(name = "IsGlobal", required = true)
    protected String isGlobal;
    @XmlElement(name = "IsPredefined", required = true)
    protected String isPredefined;

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link RulesType }
     *     
     */
    public RulesType getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesType }
     *     
     */
    public void setRules(RulesType value) {
        this.rules = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the policyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * Sets the value of the policyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyName(String value) {
        this.policyName = value;
    }

    /**
     * Gets the value of the breakBuild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakBuild() {
        return breakBuild;
    }

    /**
     * Sets the value of the breakBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakBuild(String value) {
        this.breakBuild = value;
    }

    /**
     * Gets the value of the isViolating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsViolating() {
        return isViolating;
    }

    /**
     * Sets the value of the isViolating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsViolating(String value) {
        this.isViolating = value;
    }

    /**
     * Gets the value of the isGlobal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsGlobal() {
        return isGlobal;
    }

    /**
     * Sets the value of the isGlobal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsGlobal(String value) {
        this.isGlobal = value;
    }

    /**
     * Gets the value of the isPredefined property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPredefined() {
        return isPredefined;
    }

    /**
     * Sets the value of the isPredefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPredefined(String value) {
        this.isPredefined = value;
    }

}
