//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsViolated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="violatingConditionGroups" type="{}violatingConditionGroupsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleType", propOrder = {
    "name",
    "isViolated",
    "violatingConditionGroups"
})
public class RuleType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "IsViolated", required = true)
    protected String isViolated;
    protected ViolatingConditionGroupsType violatingConditionGroups;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isViolated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsViolated() {
        return isViolated;
    }

    /**
     * Sets the value of the isViolated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsViolated(String value) {
        this.isViolated = value;
    }

    /**
     * Gets the value of the violatingConditionGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ViolatingConditionGroupsType }
     *     
     */
    public ViolatingConditionGroupsType getViolatingConditionGroups() {
        return violatingConditionGroups;
    }

    /**
     * Sets the value of the violatingConditionGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViolatingConditionGroupsType }
     *     
     */
    public void setViolatingConditionGroups(ViolatingConditionGroupsType value) {
        this.violatingConditionGroups = value;
    }

}
