//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for SCA-Risk-ReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCA-Risk-ReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RiskReportSummary" type="{}RiskReportSummaryType"/>
 *         &lt;element name="Packages" type="{}PackagesType"/>
 *         &lt;element name="Vulnerabilities" type="{}VulnerabilitiesType"/>
 *         &lt;element name="Licenses" type="{}LicensesType"/>
 *         &lt;element name="Policies" type="{}PoliciesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCA-Risk-ReportType", propOrder = {
    "riskReportSummary",
    "packages",
    "vulnerabilities",
    "licenses",
    "policies"
})

@XmlRootElement(name = "SCA-Risk-ReportType")
public class SCARiskReportType {

    @XmlElement(name = "RiskReportSummary", required = true)
    protected RiskReportSummaryType riskReportSummary;
    @XmlElement(name = "Packages", required = true)
    protected PackagesType packages;
    @XmlElement(name = "Vulnerabilities", required = true)
    protected VulnerabilitiesType vulnerabilities;
    @XmlElement(name = "Licenses", required = true)
    protected LicensesType licenses;
    @XmlElement(name = "Policies", required = true)
    protected PoliciesType policies;

    /**
     * Gets the value of the riskReportSummary property.
     * 
     * @return
     *     possible object is
     *     {@link RiskReportSummaryType }
     *     
     */
    public RiskReportSummaryType getRiskReportSummary() {
        return riskReportSummary;
    }

    /**
     * Sets the value of the riskReportSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskReportSummaryType }
     *     
     */
    public void setRiskReportSummary(RiskReportSummaryType value) {
        this.riskReportSummary = value;
    }

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link PackagesType }
     *     
     */
    public PackagesType getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagesType }
     *     
     */
    public void setPackages(PackagesType value) {
        this.packages = value;
    }

    /**
     * Gets the value of the vulnerabilities property.
     * 
     * @return
     *     possible object is
     *     {@link VulnerabilitiesType }
     *     
     */
    public VulnerabilitiesType getVulnerabilities() {
        return vulnerabilities;
    }

    /**
     * Sets the value of the vulnerabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link VulnerabilitiesType }
     *     
     */
    public void setVulnerabilities(VulnerabilitiesType value) {
        this.vulnerabilities = value;
    }

    /**
     * Gets the value of the licenses property.
     * 
     * @return
     *     possible object is
     *     {@link LicensesType }
     *     
     */
    public LicensesType getLicenses() {
        return licenses;
    }

    /**
     * Sets the value of the licenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicensesType }
     *     
     */
    public void setLicenses(LicensesType value) {
        this.licenses = value;
    }

    /**
     * Gets the value of the policies property.
     * 
     * @return
     *     possible object is
     *     {@link PoliciesType }
     *     
     */
    public PoliciesType getPolicies() {
        return policies;
    }

    /**
     * Sets the value of the policies property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoliciesType }
     *     
     */
    public void setPolicies(PoliciesType value) {
        this.policies = value;
    }

}
