//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.25 at 03:28:03 AM PST 
//


package com.checkmarx.sdk.dto.sca.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for violatingConditionGroupsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="violatingConditionGroupsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conditions" type="{}conditionsType"/>
 *         &lt;element name="violatingPackages" type="{}violatingPackagesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "violatingConditionGroupsType", propOrder = {
    "conditions",
    "violatingPackages"
})
public class ViolatingConditionGroupsType {

    @XmlElement(required = true)
    protected ConditionsType conditions;
    @XmlElement(required = true)
    protected ViolatingPackagesType violatingPackages;

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionsType }
     *     
     */
    public ConditionsType getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionsType }
     *     
     */
    public void setConditions(ConditionsType value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the violatingPackages property.
     * 
     * @return
     *     possible object is
     *     {@link ViolatingPackagesType }
     *     
     */
    public ViolatingPackagesType getViolatingPackages() {
        return violatingPackages;
    }

    /**
     * Sets the value of the violatingPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViolatingPackagesType }
     *     
     */
    public void setViolatingPackages(ViolatingPackagesType value) {
        this.violatingPackages = value;
    }

}
